/**
 * Domain model for the Poker Agent management platform.
 *
 * The platform manages PEOPLE and MONEY around an external poker room:
 *  - players join (often via an agent's referral code),
 *  - agents recruit a downline and earn rebates,
 *  - admins oversee everyone, approve cash movements, and run KYC.
 *
 * Money here is an internal ledger of chips/credits — not a payment processor.
 */

export type Role = "player" | "agent" | "admin";

export type KycStatus = "unverified" | "pending" | "verified" | "rejected";

export type AccountStatus = "active" | "suspended" | "banned";

export interface User {
  id: string;
  username: string;
  fullName: string;
  email: string;
  phone?: string;
  country?: string;
  avatarUrl?: string;
  role: Role;
  status: AccountStatus;
  kycStatus: KycStatus;
  /** The agent who referred this user (their upline). Null for the root/admin. */
  uplineAgentId: string | null;
  /** Personal referral code others can sign up with. */
  referralCode: string;
  /** ClubGG in-app member id (for reconciling chips in the agent panel). */
  clubggId?: string;
  /** ClubGG in-app nickname. */
  clubggNickname?: string;
  /** Outstanding agent-promotion request state (admin approves). */
  agentRequest?: AgentRequestStatus;
  /** Chip/credit balance in minor units (cents) of `currency`. */
  balance: number;
  /**
   * For players: how far negative this player's balance may go before their
   * direct agent must cover it (minor units, >= 0). Set by the agent as a
   * per-player risk budget; the sum across an agent's players cannot exceed
   * the agent's own balance.
   */
  creditLimit?: number;
  currency: string;
  createdAt: string; // ISO date
  lastActiveAt?: string;
  /** Aggregated lifetime poker metrics (denormalized for dashboards). */
  stats: PlayerStats;
}

export interface PlayerStats {
  handsPlayed: number;
  /** Net lifetime profit/loss in minor units. */
  netProfit: number;
  /** Total rake generated in minor units (drives agent rebates). */
  rakeGenerated: number;
  winRateBb100: number; // big blinds per 100 hands
  sessions: number;
  /** Hours spent at a table — drives VIP status (4h) and higher levels. */
  tableHours: number;
}

/** Player status label, shown as a badge on every member of a tree. */
export type MemberStatus = "new_player" | "player" | "vip_player";

/** Whether a player has an outstanding request to become an agent. */
export type AgentRequestStatus = "none" | "pending" | "rejected";

export type TransactionType =
  | "deposit"
  | "withdrawal"
  | "transfer_in"
  | "transfer_out"
  | "rake_rebate"
  | "adjustment"
  /** Admin-approved credit grant that funds an agent's balance. */
  | "agent_credit";

export type TransactionStatus = "pending" | "approved" | "rejected" | "completed";

export interface Transaction {
  id: string;
  userId: string;
  /** The counterparty for transfers, if any. */
  counterpartyId?: string;
  type: TransactionType;
  /** Signed amount in minor units: positive = credit to user, negative = debit. */
  amount: number;
  currency: string;
  status: TransactionStatus;
  note?: string;
  createdAt: string;
  /** Admin/agent who approved or recorded the entry. */
  processedBy?: string;
}

export type NotificationKind =
  | "referral"
  | "money"
  | "system"
  | "promotion"
  | "security";

export interface Notification {
  id: string;
  userId: string;
  kind: NotificationKind;
  title: string;
  body: string;
  read: boolean;
  createdAt: string;
}

/** A node in an agent's network tree, with rolled-up downline metrics. */
export interface NetworkNode {
  user: Pick<
    User,
    "id" | "username" | "fullName" | "avatarUrl" | "role" | "balance" | "currency" | "stats" | "kycStatus"
  >;
  /** Direct referrals. */
  children: NetworkNode[];
  /** Total number of descendants (whole subtree). */
  subtreeSize: number;
  /** Combined rake generated by the whole subtree (minor units). */
  subtreeRake: number;
}

export interface NetworkSummary {
  directReferrals: number;
  totalNetwork: number;
  activePlayers: number;
  networkRake: number;
  /** Estimated agent commission earned from the network (minor units). */
  commissionEarned: number;
  /** True when the agent's own balance is negative — credit & earnings frozen. */
  frozen: boolean;
  currency: string;
}

export interface AdminOverview {
  totalUsers: number;
  totalAgents: number;
  totalPlayers: number;
  pendingKyc: number;
  pendingTransactions: number;
  totalBalance: number;
  platformRake: number;
  currency: string;
}
